In [1]:
import pandas as pd

In [2]:
dataset_url_mobility = ["drive/MyDrive/Colab Notebooks/jan21.csv","drive/MyDrive/Colab Notebooks/q1.csv","drive/MyDrive/Colab Notebooks/q2.csv",
               "drive/MyDrive/Colab Notebooks/q3.csv","drive/MyDrive/Colab Notebooks/jan22.csv"]
change_param = ['retail and recreation', 'grocery and pharmacy',
       'parks', 'transit', 'workplaces', 'residential']

dataset_url_cases = ["drive/MyDrive/Colab Notebooks/Cases/jan21_cases.csv","drive/MyDrive/Colab Notebooks/Cases/q1_cases.csv","drive/MyDrive/Colab Notebooks/Cases/q2_cases.csv",
               "drive/MyDrive/Colab Notebooks/Cases/q3_cases.csv","drive/MyDrive/Colab Notebooks/Cases/jan22_cases.csv"]

dataset_url_vaccination = ["drive/MyDrive/Colab Notebooks/vaccination/jan21_vaccination.csv","drive/MyDrive/Colab Notebooks/vaccination/q1_vaccination.csv","drive/MyDrive/Colab Notebooks/vaccination/q2_vaccination.csv",
               "drive/MyDrive/Colab Notebooks/vaccination/q3_vaccination.csv"]

In [3]:
df_jan21_mobility = pd.read_csv("drive/MyDrive/Colab Notebooks/jan21.csv")

In [4]:
df_jan21_mobility.head()

,Unnamed: 0,date,retail and recreation,grocery and pharmacy,parks,transit,workplaces,residential,sub region
0,0,1/31/2021,NaN,NaN,NaN,NaN,20.760000,NaN,North and Middle Andaman
1,1,1/31/2021,12.870968,NaN,-21.516129,39.387097,17.387097,11.548387,South Andaman
2,2,1/31/2021,-22.903226,64.935484,14.129032,-9.032258,-7.806452,11.870968,Anantapuram
3,3,1/31/2021,-19.290323,34.225806,-4.580645,-19.258065,-12.354839,12.225806,Chittoor
4,4,1/31/2021,-10.387097,26.225806,-18.096774,-3.645161,-13.193548,7.838710,East Godavari

In [5]:
df_jan21_mobility['sub region'] = df_jan21_mobility['sub region'].str.upper()
df_jan21_mobility.rename(columns = {'sub region':'Districts'}, inplace = True)
df_jan21_mobility.head()

,Unnamed: 0,date,retail and recreation,grocery and pharmacy,parks,transit,workplaces,residential,Districts
0,0,1/31/2021,NaN,NaN,NaN,NaN,20.760000,NaN,NORTH AND MIDDLE ANDAMAN
1,1,1/31/2021,12.870968,NaN,-21.516129,39.387097,17.387097,11.548387,SOUTH ANDAMAN
2,2,1/31/2021,-22.903226,64.935484,14.129032,-9.032258,-7.806452,11.870968,ANANTAPURAM
3,3,1/31/2021,-19.290323,34.225806,-4.580645,-19.258065,-12.354839,12.225806,CHITTOOR
4,4,1/31/2021,-10.387097,26.225806,-18.096774,-3.645161,-13.193548,7.838710,EAST GODAVARI

In [6]:
df_jan21_cases = pd.read_csv("drive/MyDrive/Colab Notebooks/Cases/jan21_cases.csv")
df_jan21_cases['Districts'] = df_jan21_cases['Districts'].str.upper()
df_jan21_cases.shape

(641, 3)

In [16]:
indx_finding = list(df_jan21_cases['Mean Cases'])
indx_finding.sort(reverse=True)
print(indx_finding)

[631495, 394300, 381248, 301793, 263447, 228758, 131319, 126200, 124029, 119850, 118649, 102819, 98365, 95650, 95330, 94087, 87324, 86711, 81162, 80344, 75218, 70574, 67700, 67534, 66262, 62903, 62237, 62113, 60710, 59631, 59505, 59418, 58317, 57684, 56872, 56719, 55533, 55151, 54943, 54495, 53490, 52966, 52908, 51554, 51216, 51097, 50842, 50541, 48990, 48291, 47504, 46051, 45963, 44445, 43453, 43172, 41291, 41094, 39038, 37699, 36629, 35192, 33375, 32635, 32090, 31695, 30753, 29083, 29032, 28896, 28847, 28524, 28295, 26615, 26504, 26404, 26152, 25792, 25277, 25272, 25224, 24873, 24831, 24540, 24356, 23875, 23808, 23213, 23122, 22217, 22215, 22190, 22190, 22076, 22038, 21865, 21844, 21637, 21368, 21365, 21264, 21044, 20797, 20570, 20521, 20452, 20423, 20311, 20073, 20064, 19956, 19576, 19411, 19278, 19250, 19226, 19034, 18928, 18502, 18161, 18115, 17626, 17520, 17477, 17228, 17036, 17001, 16838, 16627, 16483, 16477, 16224, 16195, 16096, 16032, 15960, 15926, 15883, 15454, 15108, 15102, 14804, 14695, 14680, 14538, 14503, 14467, 14423, 14379, 14339, 14318, 14228, 14167, 14147, 14068, 14026, 13912, 13838, 13749, 13730, 13340, 13223, 13096, 12582, 12496, 12197, 12171, 12140, 12126, 12107, 11804, 11802, 11763, 11726, 11639, 11627, 11621, 11491, 11445, 11353, 11342, 11330, 11292, 11223, 11200, 11113, 11073, 11032, 11004, 10985, 10955, 10919, 10847, 10659, 10634, 10400, 10357, 10353, 10305, 10304, 10262, 10175, 10035, 9969, 9968, 9898, 9853, 9847, 9643, 9587, 9472, 9342, 9333, 9314, 9116, 9114, 9050, 9039, 9023, 8748, 8730, 8698, 8601, 8527, 8456, 8393, 8390, 8377, 8357, 8349, 8320, 8295, 8253, 8126, 8093, 8076, 8054, 8046, 8028, 8010, 7988, 7965, 7954, 7951, 7919, 7891, 7870, 7852, 7838, 7779, 7764, 7702, 7673, 7673, 7668, 7640, 7608, 7540, 7525, 7453, 7450, 7399, 7334, 7302, 7207, 7207, 7086, 7050, 6895, 6868, 6868, 6802, 6781, 6776, 6771, 6737, 6683, 6666, 6654, 6630, 6623, 6604, 6602, 6543, 6522, 6471, 6445, 6377, 6335, 6299, 6247, 6229, 6187, 6095, 6019, 6005, 5952, 5936, 5924, 5884, 5881, 5848, 5815, 5809, 5790, 5784, 5741, 5723, 5704, 5677, 5660, 5612, 5605, 5600, 5523, 5458, 5395, 5315, 5295, 5256, 5242, 5233, 5206, 5134, 5121, 5113, 5111, 5073, 5060, 5044, 5032, 4995, 4919, 4876, 4851, 4851, 4845, 4845, 4835, 4810, 4810, 4796, 4749, 4744, 4733, 4701, 4676, 4665, 4662, 4655, 4589, 4559, 4558, 4553, 4548, 4531, 4507, 4422, 4417, 4409, 4409, 4395, 4373, 4354, 4353, 4318, 4306, 4292, 4278, 4216, 4205, 4205, 4198, 4188, 4178, 4172, 4166, 4127, 4096, 4083, 4054, 4051, 4028, 4026, 4022, 4014, 4004, 4004, 3976, 3954, 3952, 3949, 3928, 3882, 3872, 3860, 3850, 3843, 3842, 3839, 3824, 3816, 3810, 3799, 3783, 3783, 3761, 3754, 3752, 3746, 3729, 3707, 3684, 3682, 3643, 3613, 3598, 3593, 3563, 3551, 3525, 3517, 3499, 3487, 3479, 3473, 3450, 3449, 3440, 3434, 3429, 3423, 3422, 3420, 3402, 3394, 3332, 3322, 3311, 3239, 3221, 3196, 3192, 3192, 3189, 3184, 3152, 3113, 3111, 3107, 3053, 3011, 3009, 2994, 2989, 2963, 2960, 2921, 2910, 2879, 2866, 2850, 2833, 2829, 2821, 2814, 2809, 2791, 2783, 2773, 2773, 2767, 2758, 2749, 2728, 2713, 2678, 2582, 2555, 2545, 2526, 2512, 2476, 2463, 2442, 2427, 2419, 2417, 2407, 2375, 2364, 2315, 2306, 2302, 2299, 2270, 2266, 2260, 2248, 2236, 2227, 2218, 2211, 2199, 2177, 2173, 2127, 2127, 2123, 2115, 2113, 2111, 2102, 2093, 2091, 2077, 2067, 2034, 2020, 1984, 1982, 1968, 1958, 1932, 1931, 1916, 1893, 1891, 1873, 1838, 1794, 1789, 1757, 1713, 1698, 1651, 1637, 1634, 1614, 1543, 1539, 1528, 1515, 1513, 1492, 1490, 1469, 1452, 1418, 1409, 1388, 1387, 1355, 1341, 1335, 1302, 1299, 1289, 1279, 1278, 1278, 1261, 1253, 1211, 1187, 1183, 1139, 1120, 1097, 1075, 1060, 1042, 1029, 969, 937, 902, 897, 859, 717, 671, 649, 605, 587, 572, 537, 521, 504, 502, 489, 474, 441, 434, 430, 428, 407, 381, 360, 339, 326, 312, 304, 291, 287, 284, 250, 245, 204, 198, 198, 186, 179, 175, 170, 142, 133, 131, 122, 119, 117, 104, 94, 85, 82, 61, 57, 47, 41, 39, 37, 35, 30, 29, 23, 23, 19, 19, 2, 0, 0, 0, 0]

In [9]:
new_df = pd.merge(df_jan21_mobility, df_jan21_cases, on= "Districts")
new_df.drop(['Unnamed: 0_x', 'Unnamed: 0_y','date'], axis=1,inplace=True)
new_df.head()

,retail and recreation,grocery and pharmacy,parks,transit,workplaces,residential,Districts,Mean Cases
0,-19.290323,34.225806,-4.580645,-19.258065,-12.354839,12.225806,CHITTOOR,86711
1,-10.387097,26.225806,-18.096774,-3.645161,-13.193548,7.838710,EAST GODAVARI,124029
2,-17.000000,23.290323,-21.548387,-8.838710,-10.774194,9.129032,GUNTUR,75218
3,-21.612903,19.612903,-18.548387,-15.258065,-16.387097,9.612903,KRISHNA,48291
4,-11.000000,26.967742,-5.548387,-7.096774,-7.096774,10.935484,KURNOOL,60710

In [10]:
print(new_df.corr())

                       retail and recreation  grocery and pharmacy     parks  \
retail and recreation               1.000000              0.282269  0.273353
grocery and pharmacy                0.282269              1.000000  0.240660
parks                               0.273353              0.240660  1.000000
transit                             0.317427              0.180726  0.179699
workplaces                          0.598912              0.311552  0.326255
residential                         0.180764              0.133517  0.215735
Mean Cases                         -0.268611             -0.106513 -0.165806

                        transit  workplaces  residential  Mean Cases
retail and recreation  0.317427    0.598912     0.180764   -0.268611
grocery and pharmacy   0.180726    0.311552     0.133517   -0.106513
parks                  0.179699    0.326255     0.215735   -0.165806
transit                1.000000    0.344579     0.164655   -0.132320
workplaces             0.344579    1.000000     0.280936   -0.250887
residential            0.164655    0.280936     1.000000    0.030490
Mean Cases            -0.132320   -0.250887     0.030490    1.000000

In [11]:
def correlation(dataset1,dataset2):
  df_mobility = pd.read_csv(dataset1)
  df_mobility['sub region'] = df_mobility['sub region'].str.upper()
  df_mobility.rename(columns = {'sub region':'Districts'}, inplace = True)
  df_cases = pd.read_csv(dataset2)
  df_cases['Districts'] = df_cases['Districts'].str.upper()
  new_df = pd.merge(df_mobility, df_cases, on= "Districts")
  new_df.drop(['Unnamed: 0_x', 'Unnamed: 0_y','date'], axis=1,inplace=True)
  
  return new_df.corr()['Mean Cases']

In [12]:
for i in dataset_url_mobility:
  for j in dataset_url_cases:
    print(correlation(i,j))

retail and recreation   -0.268611
grocery and pharmacy    -0.106513
parks                   -0.165806
transit                 -0.132320
workplaces              -0.250887
residential              0.030490
Mean Cases               1.000000
Name: Mean Cases, dtype: float64
retail and recreation   -0.273786
grocery and pharmacy    -0.105091
parks                   -0.165687
transit                 -0.133262
workplaces              -0.250007
residential              0.044039
Mean Cases               1.000000
Name: Mean Cases, dtype: float64
retail and recreation   -0.280588
grocery and pharmacy    -0.103223
parks                   -0.164595
transit                 -0.129599
workplaces              -0.240878
residential              0.065159
Mean Cases               1.000000
Name: Mean Cases, dtype: float64
retail and recreation   -0.271079
grocery and pharmacy    -0.083542
parks                   -0.134162
transit                 -0.130370
workplaces              -0.223274
residential              0.086150
Mean Cases               1.000000
Name: Mean Cases, dtype: float64

FileNotFoundError: ignored

In [21]:
def correlation_vacc(dataset1,dataset2):
  df_mobility = pd.read_csv(dataset1)
  df_mobility['sub region'] = df_mobility['sub region'].str.upper()
  df_mobility.rename(columns = {'sub region':'District'}, inplace = True)
  df_vacc = pd.read_csv(dataset2)
  df_vacc.drop(df_vacc.columns.difference(['Mean Vaccination','District']), 1, inplace=True)
  df_vacc['District'] = df_vacc['District'].str.upper()
  new_df = pd.merge(df_mobility, df_vacc, on= "District")
  #new_df.drop(['Unnamed: 0_x', 'Unnamed: 0_y','date'], axis=1,inplace=True)
  
  return new_df.corr()['Mean Vaccination']

In [22]:
for i in dataset_url_mobility:
  for j in dataset_url_vaccination:
    print(correlation_vacc(i,j))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

Unnamed: 0               0.067697
retail and recreation   -0.256964
grocery and pharmacy    -0.172070
parks                   -0.208090
transit                 -0.158226
workplaces              -0.216470
residential              0.003872
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.021391
retail and recreation   -0.241353
grocery and pharmacy    -0.135383
parks                   -0.219362
transit                 -0.142889
workplaces              -0.160337
residential              0.055439
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.004564
retail and recreation   -0.252991
grocery and pharmacy    -0.144903
parks                   -0.232254
transit                 -0.156206
workplaces              -0.175364
residential              0.035892
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.024209
retail and recreation   -0.199129
grocery and pharmacy    -0.107304
parks                   -0.185772
transit                 -0.158393
workplaces              -0.116297
residential              0.057704
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.067697
retail and recreation   -0.256518
grocery and pharmacy    -0.174577
parks                   -0.197928
transit                 -0.171448
workplaces              -0.143539
residential              0.099937
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.021391
retail and recreation   -0.279712
grocery and pharmacy    -0.167646
parks                   -0.218731
transit                 -0.182013
workplaces              -0.107711
residential              0.188172
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.004564
retail and recreation   -0.286311
grocery and pharmacy    -0.173401
parks                   -0.225041
transit                 -0.190869
workplaces              -0.111223
residential              0.178398
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.024209
retail and recreation   -0.219035
grocery and pharmacy    -0.125234
parks                   -0.168109
transit                 -0.176700
workplaces              -0.055992
residential              0.177188
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.067697
retail and recreation   -0.289189
grocery and pharmacy    -0.179028
parks                   -0.244452
transit                 -0.191886
workplaces              -0.187521
residential              0.094877
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.021391
retail and recreation   -0.266909
grocery and pharmacy    -0.146571
parks                   -0.244699
transit                 -0.154464
workplaces              -0.113260
residential              0.111407
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.004564
retail and recreation   -0.282453
grocery and pharmacy    -0.153951
parks                   -0.257097
transit                 -0.161675
workplaces              -0.124093
residential              0.107395
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.024209
retail and recreation   -0.220554
grocery and pharmacy    -0.101675
parks                   -0.196447
transit                 -0.140205
workplaces              -0.070918
residential              0.104741
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.067697
retail and recreation   -0.256061
grocery and pharmacy    -0.151859
parks                   -0.216918
transit                 -0.156211
workplaces              -0.161883
residential              0.062055
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.021391
retail and recreation   -0.236223
grocery and pharmacy    -0.125115
parks                   -0.210119
transit                 -0.129458
workplaces              -0.086675
residential              0.081586
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.004564
retail and recreation   -0.247930
grocery and pharmacy    -0.129774
parks                   -0.222805
transit                 -0.138336
workplaces              -0.091065
residential              0.076826
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.024209
retail and recreation   -0.192598
grocery and pharmacy    -0.085654
parks                   -0.175633
transit                 -0.133401
workplaces              -0.041393
residential              0.088053
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.067697
retail and recreation   -0.240241
grocery and pharmacy    -0.152953
parks                   -0.205691
transit                 -0.131812
workplaces              -0.136859
residential              0.012958
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.021391
retail and recreation   -0.232918
grocery and pharmacy    -0.138516
parks                   -0.203669
transit                 -0.117962
workplaces              -0.075459
residential              0.057258
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.004564
retail and recreation   -0.245789
grocery and pharmacy    -0.142951
parks                   -0.214898
transit                 -0.127036
workplaces              -0.079230
residential              0.049603
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64
Unnamed: 0               0.024209
retail and recreation   -0.190063
grocery and pharmacy    -0.091693
parks                   -0.166297
transit                 -0.115363
workplaces              -0.023299
residential              0.054164
Mean Vaccination         1.000000
Name: Mean Vaccination, dtype: float64